- name: ftp client installed
  hosts: all
  remote_user: vagrant
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: latest ftp version installed
    yum:
      name: vsftpd
      state: latest