- name: my tree package playbook
  hosts: all
  remote_user: centos
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: my first task to install tree
      yum:
        name: tree
        state: present
